### PR TITLE
RFC 3 Proposal

### PR DESCRIPTION
**Pull request by olivia-banks**
Proposal for RFC 3 (CNMP).

### CODE REVIEW

**Review by ehattdev — CHANGES_REQUESTED** [review]
I noticed some grammatical/spelling errors and one or two wayward letters that are not part of a word. If you can, please paste this into google docs and give it a run through grammarly or other checking software.

**Comment by olivia-banks** [comment]
I did, and it came up with nothing... I'll put it into Grammarly (I put it into word).

**Comment by ehattdev** [comment]
Looks good

**Review by ehattdev — APPROVED** [review]
Looks good (the approval didn't work the first time I tried to say this)

**Pull request merged**
